# -*- coding: utf-8 -*-
"""DBSCAN_iris.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1_5DnRACEXCaTf3spNnDrLONCEZhI709p
"""

import pandas as pd
import matplotlib.pyplot as plt
from sklearn.cluster import DBSCAN
from sklearn.preprocessing import StandardScaler

df = pd.read_csv('/Iris.csv')
df

features=['SepalLengthCm', 'SepalWidthCm']
x=df[features]

X_standardized = StandardScaler().fit_transform(x)

dbscan = DBSCAN(eps=0.5, min_samples=5)
clusters = dbscan.fit_predict(X_standardized)
clusters

centroids = pd.DataFrame(X_standardized).groupby(clusters).mean().values

plt.figure(figsize=(8, 6))
plt.scatter(x['SepalLengthCm'], x['SepalWidthCm'], c=clusters, cmap='viridis', edgecolors='k', s=50)
plt.title('DBSCAN Clustering of Mall Customer Data')
plt.xlabel('Annual Income (k$)')
plt.ylabel('Spending Score (1-100)')
plt.show()