# -*- coding: utf-8 -*-
"""DBSCAN.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/13JIRUl7zuFsY6aS8680fhzlYvizXfJeq
"""

import pandas as pd
import matplotlib.pyplot as plt
from sklearn.cluster import DBSCAN
from sklearn.preprocessing import StandardScaler

df=pd.read_csv("https://raw.githubusercontent.com/ezioauditore-tech/AI/main/datasets/Mall_Customers.csv")
df

features=['Annual Income (k$)','Spending Score (1-100)']
x=df[features]

x_stnd=StandardScaler().fit_transform(x)

dbscan=DBSCAN(eps=0.5,min_samples=5)
clusters=dbscan.fit_predict(x_stnd)
clusters

centroids = pd.DataFrame(x_stnd).groupby(clusters).mean().values

plt.figure(figsize=(8, 6))
plt.scatter(x['Annual Income (k$)'], x['Spending Score (1-100)'], c=clusters, cmap='viridis', edgecolors='k', s=50)
plt.title('DBSCAN Clustering of Mall Customer Data')
plt.xlabel('Annual Income (k$)')
plt.ylabel('Spending Score (1-100)')
plt.show()

